### ISSUE TITLE
failed at startup

### ISSUE THREAD

**Issue by timoyuen** [jacksoncage/nginx-docker#1]
when type nginx, it gives
root@9b809a38f41d:~# nginx
nginx: [emerg] directive "server" is not terminated by ";" in /etc/nginx/sites-enabled/001-docker:2

many google hits said nignx didn't recognize enviornmental variables.

**Comment by jacksoncage** [comment]
@timoyuen should be fixed now, doing a search and replace to set config on start instead of using envs inside config.
